server:
  port: 8080

spring:
  application:
    name: nacos-consumer

  cloud:
    nacos:
      discovery:
        server-addr: 120.79.14.220:8848

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  client:
    config:
      default:
#        connectTimeout: 2000
        readTimeout: 20000
        loggerLevel: BASIC
  hystrix:
    enabled: true